config/routes.rb
Rails.application.routes.draw do
  resources :tusuarios

  resources :textos

  resources :fechas

  resources :mensajes

  resources :tw_usuarios

  resources :pais

  get 'welcome/index'

  devise_for :usuarios

   root 'welcome#index'

end

app/models/texto.rb
class Texto < ActiveRecord::Base
	belongs_to :mensaje
end

app/controllers/textos_controller.rb
class TextosController < ApplicationController
  before_action :set_texto, only: [:show, :edit, :update, :destroy]

  # GET /textos
  # GET /textos.json
  def index
    @textos = Texto.all
  end

  # GET /textos/1
  # GET /textos/1.json
  def show
  end

  # GET /textos/new
  def new
    @texto = Texto.new
  end

  # GET /textos/1/edit
  def edit
  end

  # POST /textos
  # POST /textos.json
  def create
    @texto = Texto.new(texto_params)

    respond_to do |format|
      if @texto.save
        format.html { redirect_to @texto, notice: 'Texto was successfully created.' }
        format.json { render :show, status: :created, location: @texto }
      else
        format.html { render :new }
        format.json { render json: @texto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textos/1
  # PATCH/PUT /textos/1.json
  def update
    respond_to do |format|
      if @texto.update(texto_params)
        format.html { redirect_to @texto, notice: 'Texto was successfully updated.' }
        format.json { render :show, status: :ok, location: @texto }
      else
        format.html { render :edit }
        format.json { render json: @texto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textos/1
  # DELETE /textos/1.json
  def destroy
    @texto.destroy
    respond_to do |format|
      format.html { redirect_to textos_url, notice: 'Texto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_texto
      @texto = Texto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def texto_params
      params.require(:texto).permit(:texto, :idioma)
    end
end

app/helpers/textos_helper.rb
module TextosHelper
end

app/views/textos/_form.html.erb
<%= form_for(@texto) do |f| %>
  <% if @texto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@texto.errors.count, "error") %> prohibited this texto from being saved:</h2>

      <ul>
      <% @texto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_area :texto %>
  </div>
  <div class="field">
    <%= f.label :idioma %><br>
    <%= f.text_field :idioma %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/textos/edit.html.erb
<h1>Editing texto</h1>

<%= render 'form' %>

<%= link_to 'Show', @texto %> |
<%= link_to 'Back', textos_path %>

app/views/textos/index.html.erb
<h1>Listing textos</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
      <th>Idioma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textos.each do |texto| %>
      <tr>
        <td><%= texto.texto %></td>
        <td><%= texto.idioma %></td>
        <td><%= link_to 'Show', texto %></td>
        <td><%= link_to 'Edit', edit_texto_path(texto) %></td>
        <td><%= link_to 'Destroy', texto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Texto', new_texto_path %>

app/views/textos/new.html.erb
<h1>New texto</h1>

<%= render 'form' %>

<%= link_to 'Back', textos_path %>

app/views/textos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @texto.texto %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @texto.idioma %>
</p>

<%= link_to 'Edit', edit_texto_path(@texto) %> |
<%= link_to 'Back', textos_path %>