config/routes.rb
Rails.application.routes.draw do
  resources :tusuarios

  resources :textos

  resources :fechas

  resources :mensajes

  resources :tw_usuarios

  resources :pais

  get 'welcome/index'

  devise_for :usuarios

   root 'welcome#index'

end

app/models/tw_usuario.rb
class TwUsuario < ActiveRecord::Base
  has_many :mensajes
end

app/controllers/tw_usuarios_controller.rb
class TwUsuariosController < ApplicationController
  before_action :set_tw_usuario, only: [:show, :edit, :update, :destroy]

  # GET /tw_usuarios
  # GET /tw_usuarios.json
  def index
    @tw_usuarios = TwUsuario.all
  end

  # GET /tw_usuarios/1
  # GET /tw_usuarios/1.json
  def show
  end

  # GET /tw_usuarios/new
  def new
    @tw_usuario = TwUsuario.new
  end

  # GET /tw_usuarios/1/edit
  def edit
  end

  # POST /tw_usuarios
  # POST /tw_usuarios.json
  def create
    @tw_usuario = TwUsuario.new(tw_usuario_params)

    respond_to do |format|
      if @tw_usuario.save
        format.html { redirect_to @tw_usuario, notice: 'Tw usuario was successfully created.' }
        format.json { render :show, status: :created, location: @tw_usuario }
      else
        format.html { render :new }
        format.json { render json: @tw_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tw_usuarios/1
  # PATCH/PUT /tw_usuarios/1.json
  def update
    respond_to do |format|
      if @tw_usuario.update(tw_usuario_params)
        format.html { redirect_to @tw_usuario, notice: 'Tw usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @tw_usuario }
      else
        format.html { render :edit }
        format.json { render json: @tw_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tw_usuarios/1
  # DELETE /tw_usuarios/1.json
  def destroy
    @tw_usuario.destroy
    respond_to do |format|
      format.html { redirect_to tw_usuarios_url, notice: 'Tw usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tw_usuario
      @tw_usuario = TwUsuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tw_usuario_params
      params.require(:tw_usuario).permit(:username, :mensaje_id)
    end
end

app/helpers/tw_usuarios_helper.rb
module TwUsuariosHelper
end

app/views/tw_usuarios/_form.html.erb
<%= form_for(@tw_usuario) do |f| %>
  <% if @tw_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tw_usuario.errors.count, "error") %> prohibited this tw_usuario from being saved:</h2>

      <ul>
      <% @tw_usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :mensaje_id %><br>
    <%= f.text_field :mensaje_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tw_usuarios/edit.html.erb
<h1>Editing tw_usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @tw_usuario %> |
<%= link_to 'Back', tw_usuarios_path %>

app/views/tw_usuarios/index.html.erb
<h1>Listing tw_usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Mensaje</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tw_usuarios.each do |tw_usuario| %>
      <tr>
        <td><%= tw_usuario.username %></td>
        <td><%= tw_usuario.mensaje %></td>
        <td><%= link_to 'Show', tw_usuario %></td>
        <td><%= link_to 'Edit', edit_tw_usuario_path(tw_usuario) %></td>
        <td><%= link_to 'Destroy', tw_usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tw usuario', new_tw_usuario_path %>

app/views/tw_usuarios/new.html.erb
<h1>New tw_usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', tw_usuarios_path %>

app/views/tw_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tw_usuario.username %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @tw_usuario.mensaje %>
</p>

<%= link_to 'Edit', edit_tw_usuario_path(@tw_usuario) %> |
<%= link_to 'Back', tw_usuarios_path %>