config/routes.rb
Rails.application.routes.draw do
  resources :tusuarios

  resources :textos

  resources :fechas

  resources :mensajes

  resources :tw_usuarios

  resources :pais

  get 'welcome/index'

  devise_for :usuarios

   root 'welcome#index'

end

app/models/tusuario.rb
class Tusuario < ActiveRecord::Base
  belongs_to :mensaje
end

app/controllers/tusuarios_controller.rb
class TusuariosController < ApplicationController
  before_action :set_tusuario, only: [:show, :edit, :update, :destroy]

  # GET /tusuarios
  # GET /tusuarios.json
  def index
    @tusuarios = Tusuario.all
  end

  # GET /tusuarios/1
  # GET /tusuarios/1.json
  def show
  end

  # GET /tusuarios/new
  def new
    @tusuario = Tusuario.new
  end

  # GET /tusuarios/1/edit
  def edit
  end

  # POST /tusuarios
  # POST /tusuarios.json
  def create
    @tusuario = Tusuario.new(tusuario_params)

    respond_to do |format|
      if @tusuario.save
        format.html { redirect_to @tusuario, notice: 'Tusuario was successfully created.' }
        format.json { render :show, status: :created, location: @tusuario }
      else
        format.html { render :new }
        format.json { render json: @tusuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tusuarios/1
  # PATCH/PUT /tusuarios/1.json
  def update
    respond_to do |format|
      if @tusuario.update(tusuario_params)
        format.html { redirect_to @tusuario, notice: 'Tusuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @tusuario }
      else
        format.html { render :edit }
        format.json { render json: @tusuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tusuarios/1
  # DELETE /tusuarios/1.json
  def destroy
    @tusuario.destroy
    respond_to do |format|
      format.html { redirect_to tusuarios_url, notice: 'Tusuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tusuario
      @tusuario = Tusuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tusuario_params
      params.require(:tusuario).permit(:username, :mensaje_id)
    end
end

app/helpers/tusuarios_helper.rb
module TusuariosHelper
end

app/views/tusuarios/_form.html.erb
<%= form_for(@tusuario) do |f| %>
  <% if @tusuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tusuario.errors.count, "error") %> prohibited this tusuario from being saved:</h2>

      <ul>
      <% @tusuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :mensaje_id %><br>
    <%= f.text_field :mensaje_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tusuarios/edit.html.erb
<h1>Editing tusuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @tusuario %> |
<%= link_to 'Back', tusuarios_path %>

app/views/tusuarios/index.html.erb
<h1>Listing tusuarios</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Mensaje</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tusuarios.each do |tusuario| %>
      <tr>
        <td><%= tusuario.username %></td>
        <td><%= tusuario.mensaje %></td>
        <td><%= link_to 'Show', tusuario %></td>
        <td><%= link_to 'Edit', edit_tusuario_path(tusuario) %></td>
        <td><%= link_to 'Destroy', tusuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tusuario', new_tusuario_path %>

app/views/tusuarios/new.html.erb
<h1>New tusuario</h1>

<%= render 'form' %>

<%= link_to 'Back', tusuarios_path %>

app/views/tusuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tusuario.username %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @tusuario.mensaje %>
</p>

<%= link_to 'Edit', edit_tusuario_path(@tusuario) %> |
<%= link_to 'Back', tusuarios_path %>