config/routes.rb
Rails.application.routes.draw do
  resources :tusuarios

  resources :textos

  resources :fechas

  resources :mensajes

  resources :tw_usuarios

  resources :pais

  get 'welcome/index'

  devise_for :usuarios

   root 'welcome#index'

end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
  belongs_to :tw_usuario
  has_one :fecha
  has_one :texto
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]

  def index
    @mensajes = Mensaje.all
    respond_with(@mensajes)
  end

  def show
    respond_with(@mensaje)
  end

  def new
    @mensaje = Mensaje.new
    respond_with(@mensaje)
  end

  def edit
  end

  def create
    @mensaje = Mensaje.new(mensaje_params)
    @mensaje.save
    respond_with(@mensaje)
  end

  def update
    @mensaje.update(mensaje_params)
    respond_with(@mensaje)
  end

  def destroy
    @mensaje.destroy
    respond_with(@mensaje)
  end

  private
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    def mensaje_params
      params.require(:mensaje).permit(:fecha_id, :texto_id)
    end
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/views/mensajes/_form.html.erb
<%= form_for(@mensaje) do |f| %>
  <% if @mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensaje.errors.count, "error") %> prohibited this mensaje from being saved:</h2>

      <ul>
      <% @mensaje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha_id %><br>
    <%= f.text_field :fecha_id %>
  </div>
  <div class="field">
    <%= f.label :texto_id %><br>
    <%= f.text_field :texto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mensajes/edit.html.erb
<h1>Editing mensaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @mensaje %> |
<%= link_to 'Back', mensajes_path %>

app/views/mensajes/index.html.erb
<h1>Listing mensajes</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr>
        <td><%= mensaje.fecha %></td>
        <td><%= mensaje.texto %></td>
        <td><%= link_to 'Show', mensaje %></td>
        <td><%= link_to 'Edit', edit_mensaje_path(mensaje) %></td>
        <td><%= link_to 'Destroy', mensaje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mensaje', new_mensaje_path %>

app/views/mensajes/new.html.erb
<h1>New mensaje</h1>

<%= render 'form' %>

<%= link_to 'Back', mensajes_path %>

app/views/mensajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @mensaje.fecha %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @mensaje.texto %>
</p>

<%= link_to 'Edit', edit_mensaje_path(@mensaje) %> |
<%= link_to 'Back', mensajes_path %>